server:
  port: 8080
  servlet:
    context-path: /identity/api/v1
spring:
  application:
    name: identity-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/e_identity_service
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  base64-secret: cjfj7FWvhyO66IPFwEtdlx2uQYVvBGL7NL6quv81W8v4cITO893aTdYld+FipAkHDZ4RxnaLN3bXkNskACbWFA==
  access-token: 86400
  refresh-token: 2592000